-- Migration: v55_hover_material_list
-- Filed by: gh-1438 migration history backfill batch 1 (Code lane)
-- Date filed: 2026-09-02
--
-- STATUS: ALREADY APPLIED. This file is a post-apply trace added by the
-- gh-1438 migration history backfill (issue #1438, batch 1, non-money
-- orphans, oldest first) -- it does NOT re-apply anything; merging this PR
-- is a no-op against the database. Applied to production
-- (yeszghaspzwwstvsrioa) 2026-04-23T23:16:52Z, recorded in
-- supabase_migrations.schema_migrations as version 20260423231652, name
-- "v55_hover_material_list". NEVER RE-RUN.
--
-- PROVENANCE: sourced verbatim via a read-only SELECT against
-- supabase_migrations.schema_migrations.statements for this version,
-- 2026-09-02, gh-1438 backfill batch 1. No SQL was executed against
-- production to produce this file -- no prior repo record for this
-- version was found; this is the first repo record of it.
--
-- NOTE: this is the SECOND of two distinct applied migrations sharing the
-- name "v55_hover_material_list" -- the first is version 20260423182441
-- (filed alongside this one in the same batch). This row's statement is a
-- single-line ALTER TABLE, materially shorter than the first version's
-- (which also adds a GIN index), consistent with this being a later
-- re-run/correction against a different code path rather than a
-- duplicate record of the same apply.

ALTER TABLE hover_orders ADD COLUMN IF NOT EXISTS material_list JSONB;
