-- Migration: v103_fix_cert_verification_quality_security_invoker
-- Filed by: gh-1438 migration history backfill batch 3 (Code lane)
-- Date filed: 2026-09-03
--
-- STATUS: ALREADY APPLIED. This file is a post-apply trace added by the
-- gh-1438 migration history backfill (issue #1438, batch 3, non-money
-- orphans, oldest first) -- it does NOT re-apply anything; merging this PR
-- is a no-op against the database. Applied to production
-- (yeszghaspzwwstvsrioa) 2026-08-10T21:33:25Z, recorded in
-- supabase_migrations.schema_migrations as version 20260810213325, name
-- "v103_fix_cert_verification_quality_security_invoker". NEVER RE-RUN.
--
-- PROVENANCE: sourced verbatim via a read-only SELECT against
-- supabase_migrations.schema_migrations.statements for this version,
-- 2026-09-03, gh-1438 backfill batch 3. No SQL was executed against
-- production to produce this file -- no prior repo record for this
-- version was found; this is the first repo record of it.

-- v103 -- gh-530 (1 of 4 ERROR security_definer_view findings)
-- cert_verification_quality_by_manufacturer is a backend/admin reporting view
-- (aggregate counts/percentages, no PII) with NO grant to anon/authenticated
-- and no application code queries it client-side (grep confirmed: only SQL
-- migration files reference it). It is only ever queried via service_role,
-- which bypasses RLS regardless of security_invoker -- so flipping this to
-- security_invoker=true has zero functional impact and clears the linter
-- ERROR cleanly. Safe, isolated fix.
ALTER VIEW public.cert_verification_quality_by_manufacturer SET (security_invoker = true);
