/**
 * [gh-2078b / D-330] Server-side Meta Conversions API (CAPI) `Purchase` event
 * for measurement-order ($15 Hover report) payments, sent from stripe-webhook.
 *
 * WHY THIS EXISTS. #2078 / D-330: Dustin approved server-side `Purchase`
 * events so Meta's homeowner ad set can optimise toward a real outcome
 * instead of landing-page-views (comment 5777193662). The client pixel
 * (`fbq('track','Purchase', ...)`, gh-2078a / help-measurements/page.tsx)
 * already fires on the confirmed-charge success path; this is the
 * server-side twin, sent from the payment authority (Stripe, via this
 * webhook) rather than the browser, so it lands even when the browser tab
 * closes before the client-side call completes and is not affected by ad
 * blockers.
 *
 * Pure / testable decision logic lives here (no network, no Deno.env, no
 * Supabase client) — see meta-capi.test.ts. The one function that actually
 * calls out to Meta (`postCapiEvent`) is deliberately thin and lives in
 * index.ts's handler, which owns the Supabase lookups, the timeout, and the
 * "never fail the webhook" isolation (acceptance criterion 2).
 *
 * DEDUPLICATION (Meta dedupes client pixel + server CAPI on the SAME
 * `event_name` + `event_id`): `buildCapiEventId` is deterministic —
 * `measurement_purchase:<paymentIntentId>` — specifically so gh-2078a's
 * client pixel call can compute the IDENTICAL string and pass it as
 * `fbq('track','Purchase', {...}, {eventID: 'measurement_purchase:' + pi})`.
 * As of this PR the client call (lib/track.ts's `fbqTrack('Purchase', ...)`
 * call sites in help-measurements/page.tsx) does NOT pass an eventID at all
 * — flagged as a `Q:` on #2078 with this exact recommended default; until
 * gh-2078a adopts it, Meta will count two distinct Purchase events per
 * transaction (over-counted, not under-counted — the CAPI side alone is
 * still correct and deduplicates against ITSELF on Stripe's at-least-once
 * webhook redelivery, which is caught upstream by index.ts's
 * `stripe_webhook_events` ledger before this code ever runs).
 *
 * TEST-MODE ISOLATION (acceptance criterion 4): a Stripe test-mode event
 * (`!paymentIntent.livemode`) or an `is_test` claim must never land in
 * Meta's PRODUCTION event stream unmarked. Meta's own mechanism for this is
 * a per-pixel `test_event_code` (Events Manager -> Test Events), which is
 * NOT the same thing as `livemode` and is not generated by this PR. Decision
 * (`shouldSendCapiEvent`): real production traffic always sends; test
 * traffic sends ONLY if `META_CAPI_TEST_EVENT_CODE` is configured, otherwise
 * it is skipped outright. That means the sanctioned Stripe test-mode walk
 * this issue's closes-on requires will legitimately produce ZERO Meta CAPI
 * event unless that secret is set first — documented in the PR body and the
 * task report, not silently worked around.
 */

/** Meta Graph API version this integration targets. Bump deliberately, not casually. */
export const META_CAPI_API_VERSION = "v21.0";

/**
 * Pixel id from Dustin's ruling, #2078 comment 5777193662 ("Pixel id
 * 800470107451795"). Not a secret — pixel ids are public (they ship in the
 * client-side snippet) — so this is a constant, not an env var, matching how
 * js/meta-pixel-gate.js already embeds it client-side.
 */
export const META_CAPI_PIXEL_ID = "800470107451795";

/** The $15 RoofScope / Hover measurement report price (D-291). */
export const MEASUREMENT_PURCHASE_VALUE_USD = 15.0;

const VARIANT_SHAPE_RE = /^[a-z0-9]{1,8}$/;

/**
 * Deterministic CAPI `event_id` for a measurement-order purchase. See the
 * file header's DEDUPLICATION note — this exact string is the recommended
 * default posted as a `Q:` on #2078 for gh-2078a's client pixel call to
 * match.
 */
export function buildCapiEventId(paymentIntentId: string): string {
  return `measurement_purchase:${paymentIntentId}`;
}

/**
 * gh-2078b acceptance criterion 4 — see file header TEST-MODE ISOLATION.
 * Pure decision, no network: real (livemode, non-is_test) traffic always
 * sends; test traffic sends only when a real Meta test_event_code is
 * configured.
 */
export function shouldSendCapiEvent(params: {
  livemode: boolean;
  claimIsTest: boolean;
  testEventCode: string | null;
}): boolean {
  const isTestTraffic = !params.livemode || params.claimIsTest;
  if (!isTestTraffic) return true;
  return params.testEventCode !== null && params.testEventCode !== "";
}

/**
 * Bounded shape check for the router variant (mirrors react-app's
 * lib/track.ts `sanitizeVariantParam`) — never forward an unbounded string
 * from PaymentIntent metadata into a third-party API call. Falls back to
 * 'unknown', matching the client's own fallback when no variant was ever
 * captured. See file's "known gap" note in the PR body: `variant` is not
 * currently threaded into PaymentIntent metadata at all (create-payment-intent
 * appends only claim_id/type), so this will read 'unknown' until that is
 * wired up — flagged as a Q: on #2078, not silently faked here.
 */
export function sanitizeCapiVariant(value: string | undefined | null): string {
  return typeof value === "string" && VARIANT_SHAPE_RE.test(value) ? value : "unknown";
}

export interface BuildCapiPurchasePayloadInput {
  paymentIntentId: string;
  /** Unix seconds. */
  eventTimeSeconds: number;
  valueUsd: number;
  variant: string;
  /** SHA-256 hex digest of the lowercased+trimmed email, or null if unresolvable. Never raw PII. */
  hashedEmail: string | null;
  /** Non-null only when this send has passed shouldSendCapiEvent's test-traffic gate. */
  testEventCode: string | null;
  eventSourceUrl?: string;
}

/**
 * Builds the Meta CAPI `/events` request body. Pure — no network, no env
 * reads. `user_data.em` is the ONLY user-identifying field sent, and only
 * ever as a SHA-256 hash (acceptance criterion 1: "never raw PII") — if no
 * email could be resolved, `em` is simply omitted (Meta accepts a purchase
 * event with empty user_data, at reduced match quality; it does not reject
 * it).
 *
 * Known limitation, stated rather than faked: this webhook has no browser
 * context (Stripe calls it server-to-server), so it cannot supply `fbp`,
 * `fbc`, `client_ip_address`, or `client_user_agent` — all of which improve
 * Meta's match quality. A future iteration could have the client capture
 * `fbp`/`fbc` at checkout time and carry them through PaymentIntent metadata
 * for this handler to forward; out of scope for this PR (see report).
 */
export function buildCapiPurchasePayload(
  input: BuildCapiPurchasePayloadInput,
): Record<string, unknown> {
  const userData: Record<string, unknown> = {};
  if (input.hashedEmail) userData.em = [input.hashedEmail];

  const eventPayload: Record<string, unknown> = {
    event_name: "Purchase",
    event_time: input.eventTimeSeconds,
    event_id: buildCapiEventId(input.paymentIntentId),
    action_source: "website",
    user_data: userData,
    custom_data: {
      value: input.valueUsd,
      currency: "USD",
      content_name: "measurement_report",
      content_type: "product",
      variant: input.variant,
    },
  };
  if (input.eventSourceUrl) eventPayload.event_source_url = input.eventSourceUrl;

  const body: Record<string, unknown> = { data: [eventPayload] };
  if (input.testEventCode) body.test_event_code = input.testEventCode;
  return body;
}

/**
 * SHA-256 hex digest of the lowercased, trimmed email — Meta's required
 * `em` hashing convention (acceptance criterion 1). Uses the platform Web
 * Crypto API already relied on elsewhere in this file's sibling
 * (index.ts's `verifyStripeSignature`) — no external hashing dependency.
 */
export async function hashEmailSha256(rawEmail: string): Promise<string> {
  const normalized = rawEmail.trim().toLowerCase();
  const bytes = new TextEncoder().encode(normalized);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** PaymentIntent metadata.type values this handler treats as a measurement-order purchase. */
export const MEASUREMENT_ORDER_PI_TYPES: ReadonlySet<string> = new Set([
  "measurement_order",
  "hover_measurement", // legacy value, still emitted by the older frontend path (create-measurement-order.ts)
]);

/**
 * [gh-2107 / D-330 half 2] The advertising-sharing opt-out (privacy policy Section 12).
 *
 * Dustin's ruling "b." (#2078 comment 5801822166): a stored `profiles.ad_sharing_opt_out` flag, set by a browser's Global
 * Privacy Control signal or by an admin recording a support email, and "the CAPI Purchase send skips any opted-out person".
 *
 * Only the boolean `true` opts a person out (NULL = never recorded; false = cleared). FAIL CLOSED on a failed lookup: if the
 * profile could not be read, whether this person opted out is unknown, and sending to an opted-out person is the harm this
 * exists to prevent, whereas a skipped Purchase is a lost signal that a later, healthy read does not repeat. A missing row
 * with no error means there is no record of any opt-out and is not skipped.
 */
export interface AdSharingProfile {
  ad_sharing_opt_out?: boolean | null;
}

export function shouldSkipForAdSharingOptOut(
  profile: AdSharingProfile | null,
  lookupFailed: boolean,
): { skip: boolean; reason: "lookup_failed" | "opted_out" | null } {
  if (lookupFailed) return { skip: true, reason: "lookup_failed" };
  if (profile?.ad_sharing_opt_out === true) return { skip: true, reason: "opted_out" };
  return { skip: false, reason: null };
}

/**
 * [gh-2107, REVIEW: FAIL B2 / LEGAL-READ: FAIL] The person a Purchase belongs to must be RESOLVABLE, or nothing is sent.
 *
 * The opt-out read (shouldSkipForAdSharingOptOut) needs a user id, and the user id comes from the claim. If the claim lookup
 * errored, or the PaymentIntent carries no claim_id, or the claim has no user, the opt-out status of the person cannot be
 * read, and "an unknown opt-out must not be sent to" applies exactly as it does to a failed profile read. (No email would go
 * out on that path, but the event_id is the same key the browser pixel sends with the _fbp cookie, which makes it a linkable
 * identifier for someone whose opt-out we could not read.)
 */
export function decideCapiPerson(input: {
  claimId: string | null | undefined;
  claimLookupFailed: boolean;
  userId: string | null | undefined;
}): { skip: boolean; reason: "claim_lookup_failed" | "no_claim_id" | "no_user_id" | null } {
  if (input.claimLookupFailed) return { skip: true, reason: "claim_lookup_failed" };
  if (!input.claimId) return { skip: true, reason: "no_claim_id" };
  if (!input.userId) return { skip: true, reason: "no_user_id" };
  return { skip: false, reason: null };
}

/**
 * The Purchase value is what Stripe actually charged (D-181: the price lives server-side in platform_settings and can move),
 * in dollars. Anything that is not a positive integer number of cents falls back to the constant rather than sending Meta a
 * made-up value.
 */
export function capiPurchaseValueUsd(amountCents: unknown, fallbackUsd: number): number {
  return typeof amountCents === "number" && Number.isInteger(amountCents) && amountCents > 0 ? amountCents / 100 : fallbackUsd;
}

/**
 * What may be logged, or written to platform_alerts_log, about a failed Meta call: the numeric error code and a short type
 * token, never the message (which can echo request data). Anything else is "unparsed".
 */
export function safeMetaErrorSummary(body: string): string {
  try {
    const e = (JSON.parse(body) as { error?: { code?: unknown; type?: unknown } } | null)?.error;
    if (!e || typeof e !== "object") return "unparsed";
    const parts: string[] = [];
    if (typeof e.code === "number" && Number.isFinite(e.code)) parts.push(`code=${e.code}`);
    if (typeof e.type === "string" && /^[A-Za-z0-9_]{1,40}$/.test(e.type)) parts.push(`type=${e.type}`);
    return parts.length ? parts.join(" ") : "unparsed";
  } catch {
    return "unparsed";
  }
}
